### ISSUE TITLE
[Bug] every added job throws `corrupted returnvalue` when moved to active

### ISSUE THREAD

**Issue by marshall007** [OptimalBits/bull#624]
At least in `v3.0.0-rc.4`, every time you add a job, the `returnvalue` is initially `undefined`. I think this is because `returnvalue` is not one of the keys that gets set in `scripts.addJob`. The result is when these jobs are moved to active they all throw the `corrupted returnvalue` error. This makes it difficult to debug actual problems locally.

**Comment by Gourmentt** [comment]
Agreed, this issue happened to me as well, resultValue is undefined.
place - job.js:362

**Comment by manast** [comment]
Can you please verify if this issue is still present in rc8?

**Comment by manast** [comment]
I will reopen if the issue is still there.

**Comment by mesaugat** [comment]
Yes, I am getting this error with `"bull": "^3.0.0"`.

**Comment by playahater** [comment]
Hello,
I'm using using `"bull": "^3.2.0"` and also getting this error.
It is visible only when NODE_DEBUG=bull is enabled.

```
BULL 8052: Job added 1
BULL 8052: corrupted returnvalue: undefined { value:
   SyntaxError: Unexpected token u in JSON at position 0
       at JSON.parse (<anonymous>)
       at Object.tryCatch (/srv/http/career/node_modules/bull/lib/utils.js:6:15)
       at getReturnValue (/srv/http/career/node_modules/bull/lib/job.js:494:21)
       at Function.Job.fromJSON (/srv/http/career/node_modules/bull/lib/job.js:476:21)
       at /srv/http/career/node_modules/bull/lib/queue.js:927:23
       at tryCatcher (/srv/http/career/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/srv/http/career/node_modules/bluebird/js/release/promise.js:509:35)
       at Promise._settlePromise (/srv/http/career/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/srv/http/career/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/srv/http/career/node_modules/bluebird/js/release/promise.js:693:18)
       at Promise._fulfill (/srv/http/career/node_modules/bluebird/js/release/promise.js:638:18)
       at PromiseArray._resolve (/srv/http/career/node_modules/bluebird/js/release/promise_array.js:126:19)
       at PromiseArray._promiseFulfilled (/srv/http/career/node_modules/bluebird/js/release/promise_array.js:144:14)
       at PromiseArray._iterate (/srv/http/career/node_modules/bluebird/js/release/promise_array.js:114:31)
       at PromiseArray.init [as _init] (/srv/http/career/node_modules/bluebird/js/release/promise_array.js:78:10)
       at Promise._settlePromise (/srv/http/career/node_modules/bluebird/js/release/promise.js:566:21)
       at Promise._settlePromise0 (/srv/http/career/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/srv/http/career/node_modules/bluebird/js/release/promise.js:693:18)
       at Async._drainQueue (/srv/http/career/node_modules/bluebird/js/release/async.js:133:16)
       at Async._drainQueues (/srv/http/career/node_modules/bluebird/js/release/async.js:143:10)
       at Immediate.Async.drainQueues (/srv/http/career/node_modules/bluebird/js/release/async.js:17:14)
       at runCallback (timers.js:781:20) }
```

**Comment by PauloFerreira25** [comment]
Hi, same here.
```
BULL 15297: Job added 344
BULL 15297: corrupted returnvalue: undefined { value: 
   SyntaxError: Unexpected token u in JSON at position 0
       at JSON.parse (<anonymous>)
       at Object.tryCatch (/sistema/tblu/d-backend-bull/node_modules/bull/lib/utils.js:6:15)
       at getReturnValue (/sistema/tblu/d-backend-bull/node_modules/bull/lib/job.js:494:21)
       at Function.Job.fromJSON (/sistema/tblu/d-backend-bull/node_modules/bull/lib/job.js:476:21)
       at /sistema/tblu/d-backend-bull/node_modules/bull/lib/queue.js:927:23
       at tryCatcher (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise.js:509:35)
       at Promise._settlePromise (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise.js:693:18)
       at Promise._fulfill (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise.js:638:18)
       at PromiseArray._resolve (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise_array.js:126:19)
       at PromiseArray._promiseFulfilled (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise_array.js:144:14)
       at PromiseArray._iterate (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise_array.js:114:31)
       at PromiseArray.init [as _init] (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise_array.js:78:10)
       at Promise._settlePromise (/sistema/tblu/d-backend-bull/node_modules/bluebird/js/release/promise.js:566:21) }
```

**Comment by manast** [comment]
The fix is in master, a new release is imminent.

**Comment by manast** [comment]
fixed in v3.3.0

**Comment by PauloFerreira25** [comment]
thank you so much

**Comment by polonel** [comment]
I'm still seeing this error and I'm curious if its a cause to my issue at #731 and I'm on 3.3.1

```
BULL 18324: Job added 21
BULL 18324: corrupted returnvalue: undefined { value: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.tryCatch (c:\NodeApps\cloud.trudesk.io\node_modules\bull\lib\utils.js:6:15)
    at getReturnValue (c:\NodeApps\cloud.trudesk.io\node_modules\bull\lib\job.js:497:21)
    at Function.Job.fromJSON (c:\NodeApps\cloud.trudesk.io\node_modules\bull\lib\job.js:479:21)
    at c:\NodeApps\cloud.trudesk.io\node_modules\bull\lib\queue.js:935:23
    at tryCatcher (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:509:35)
    at Promise._settlePromise (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise_array.js:144:14)
    at PromiseArray._iterate (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise_array.js:114:31)
    at PromiseArray.init [as _init] (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise_array.js:78:10)
    at Promise._settlePromise (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (c:\NodeApps\cloud.trudesk.io\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20) }

**Comment by Unibozu** [comment]
Same here. Using bull 3.3.1
